version: '3.8'

services:
  backend:
    build:
      context: ./backend/stakeholders
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: tourism
      JWT_SECRET: "JelfesyMS6HKEZerkegVucBD0GMcgJN0ZTzvuXxnG/0="
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tourism
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/stakeholders/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 20
    command: --default-authentication-plugin=mysql_native_password

  mongodb:
    image: mongo:6
    container_name: tourism-app-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 30s
      timeout: 5s
      retries: 20

  blog:
    build:
      context: ./backend/blog
    environment:
      MONGO_URI: "mongodb://mongodb:27017"
      MONGO_DB: "tourism"
      MONGO_COLLECTION: "blogs"
      JWT_SECRET: "JelfesyMS6HKEZerkegVucBD0GMcgJN0ZTzvuXxnG/0="
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - "8082:8080"
    restart: unless-stopped

  # --- KT2 #10: Tour servis (Java + Spring Boot + MySQL) ---
  tour-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tourdb
    volumes:
      - tour_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ppassword"]
      interval: 5s
      timeout: 10s
      retries: 20
    command: --default-authentication-plugin=mysql_native_password

  tour:
    build:
      context: ./backend/tour
      dockerfile: Dockerfile
    environment:
      DB_URL: "jdbc:mysql://tour-mysql:3306/tourdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
      DB_USER: "root"
      DB_PASSWORD: "password"
      JWT_SECRET: JelfesyMS6HKEZerkegVucBD0GMcgJN0ZTzvuXxnG/0=
    depends_on:
      tour-mysql:
        condition: service_healthy
    ports:
      - "8083:8083"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:8081
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_started
    restart: unless-stopped

volumes:
  mongo_data:
  mysql_data:
  tour_mysql_data:
