version: "3.9"

services:
  prometheus:
    image: prom/prometheus:v2.55.0
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=15d
      - --web.enable-lifecycle
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/rules.yml:/etc/prometheus/rules.yml:ro   # ← obavezno
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks: [monitoring]


  grafana:
    image: grafana/grafana:11.2.0
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=localhost
      - GF_SERVER_ROOT_URL=http://localhost:3001/
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3001:3000"
    depends_on: [prometheus, loki, jaeger]
    networks: [monitoring]

  node-exporter:
    image: quay.io/prometheus/node-exporter:v1.8.1
    container_name: node-exporter
    pid: "host"
    command:
      - --path.rootfs=/host
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($|/)
    volumes:
      - /:/host:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    restart: unless-stopped
    ports:
      - "9100:9100"
    networks: [monitoring]

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    container_name: cadvisor
    privileged: true
    command:
      - -logtostderr
      - --housekeeping_interval=10s
      - --docker_only=false
      - --store_container_labels=true
    ports:
      - "8088:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro   
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    restart: unless-stopped
    networks:
      - monitoring
     


  loki:
    image: grafana/loki:2.9.8
    container_name: loki
    command: -config.file=/etc/loki/local-config.yml
    volumes:
      - ./loki/loki-config.yml:/etc/loki/local-config.yml:ro
      - loki_data:/loki
    ports:
      - "3100:3100"
    networks: [monitoring]

  promtail:
    image: grafana/promtail:2.9.8
    container_name: promtail
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./promtail/promtail-config.yml:/etc/promtail/config.yml:ro
    depends_on: [loki]
    networks: [monitoring]


  jaeger:
    image: jaegertracing/jaeger:2.0.0
    container_name: jaeger
    command:
      - --set
      - receivers.otlp.protocols.http.endpoint=0.0.0.0:4318
      - --set
      - receivers.otlp.protocols.grpc.endpoint=0.0.0.0:4317
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    networks: [monitoring]

networks:
  monitoring:
    name: observability_net

volumes:
  prometheus_data:
  grafana_data:
  loki_data:
