ALTER TABLE key_points
  MODIFY COLUMN id CHAR(36) NOT NULL,
  MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

Ako koristiš CHAR(36) svuda, proveri i sim_locations pa po potrebi odkomentariši:
 ALTER TABLE sim_locations
   MODIFY COLUMN id CHAR(36) NOT NULL,
   MODIFY COLUMN user_id CHAR(36) NOT NULL;